### ISSUE TITLE
Unable to install `app-admin/Lmod`

### ISSUE THREAD

**Issue by victorusu** [EESSI/gentoo-overlay#10]
After [this PR](https://github.com/EESSI/gentoo-overlay/commit/182729ab1f2440f690269c73c03db698abe9756c) was merged I cannot install `app-admin/Lmod` anymore.
I get the following error:
```
checking for valid Lua version... 5.1
checking for lua modules: posix

Error: The follow lua module(s) are missing:  posix

You can not run Lmod without:  posix

!!! Please attach the following file when seeking support:
!!! /apps/gentoo-prefix/var/tmp/portage/app-admin/Lmod-8.3.17/work/Lmod-8.3.17/config.log
 * ERROR: app-admin/Lmod-8.3.17::eessi failed (configure phase):
 *   econf failed
```

If I revert back to the original file, I am able to compile it again...
```
>>> Installing (1 of 1) app-admin/Lmod-8.3.17::eessi
 * You should add the following to your ~/.bashrc to use Lmod:
 * [ -f /usr/lmod/lmod/init/bash ] && \ 
 * 	source /usr/lmod/lmod/init/bash

>>> Recording app-admin/Lmod in "world" favorites file...
```

**Comment by bedroge** [comment]
I just tried to reproduce the issue in a clean prefix environment, but for me it worked fine. Did you install the luaposix version from the eessi repository? The central gentoo repo now includes a similar version (see #9).

**Comment by victorusu** [comment]
I also tried using a clean prefix... I installed the `luaposix` from the eessi project
```
...
>>> Installing (2 of 2) dev-lua/luaposix-35.0::eessi

>>> Recording dev-lua/luaposix in "world" favorites file...
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.
```

I trigger again the destruction and construction of the VM to check what went wrong with more details.

**Comment by victorusu** [comment]
Yes! You are right!
When I started over the VM, Lmod installed perfectly.
Sorry for the trouble.
