### ISSUE TITLE
rename '2020' set to '2020.08'?

### ISSUE THREAD

**Issue by boegel** [EESSI/gentoo-overlay#14]
If the `2020` in `etc/portage/sets/2020` is supposed to be a version, I think it makes more sense to use something like `2020.08` (the set that we started defining in Aug 2020)?

Not sure if it's worth updating the version on the fly if we add additional packages to that set, I'm not sure in which other places this needs to be changed accordingly...

cc @bedroge @peterstol

**Comment by bedroge** [comment]
I think it makes sense to change it, then the name is the same as the version in our path on /cvmfs.

**Comment by peterstol** [comment]
Agree, see PR #15
