### ISSUE TITLE
Unmask packages for aarch64 + ppc64le

### ISSUE THREAD

**Issue by bedroge** [EESSI/gentoo-overlay#26]
The following packages are masked and should be unmasked for `ppc64le`:
```
sys-cluster/lmod
dev-lua/luaposix
dev-lua/lua-bit32
```

**Comment by terjekv** [comment]
Also, they should be unmasked for arm.

**Comment by boegel** [comment]
Did we hack around this for the 2021.02 compat layer installations?

**Comment by terjekv** [comment]
@bedroge suggested the following, which is what I did:

> As a quicky and dirty fix I used the following on ppc64le, should also work for aarch64. When the playbook crashes on the package installation step, add the following lines to the already existing file ${EPREFIX}/etc/portage/package.accept_keywords  (EPREFIX for aarch64 is /cvmfs/pilot.eessi-hpc.org/2021.02/compat/linux/aarch64 ):
```
sys-cluster/lmod ~amd64
dev-lua/luaposix ~amd64
dev-lua/lua-bit32 amd64
```

**Comment by boegel** [comment]
It looks like @epsilon-0 is actively looking into fixing Lmod for `arm64` and `ppc64`, see https://bugs.gentoo.org/773313

**Comment by boegel** [comment]
For future reference, the error that occurs during the installation of our compatibility layer:

```
TASK [compatibility_layer : Install package set ['eessi-2021.02-linux-aarch64']] 
```

```
!!! All ebuilds that could satisfy "sys-cluster/lmod" have been masked.
!!! One of the following masked packages is required to complete your request:
- sys-cluster/lmod-9999::gentoo (masked by: missing keyword)
- sys-cluster/lmod-8.4.20::gentoo (masked by: missing keyword)

(dependency required by "@eessi-2021.02-linux-aarch64" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

**Comment by epsilon-0** [comment]
\o/ glad to be of help :heart: 
This is a very interesting project!

I also help around in the [Gentoo Science](https://github.com/gentoo/sci) project, so let me know if you need any specifics fixes/packages there.
It's really awesome to see Gentoo being used, so I'm up for helping add to this.

**Comment by boegel** [comment]
@epsilon-0 Is there a high-level overview of what the focus of the Gentoo Science project is, like a presentation or something like that? It would be interesting to see where we align and diverge in terms of approach and goals...

**Comment by epsilon-0** [comment]
@boegel I don't think we have such a concrete picture in mind.
Quite a few members of the Gentoo Science team manage their own mini (or not so mini) research clusters for their labs, so most of the work is done where the developer gets a benefit, while of course trying to keep things sane and usable by others.
As with most open source projects, its a conglomeration of people benefiting from each others work.
But helping more concrete projects like yours sounds like it should also benefit others, given that your projects are widely used :)
